/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DescriptorEntry {
    id: bigint;
    personType: PersonType;
    name: string;
    faceDescriptor: Array<number>;
}
export interface Stats {
    activeMonths: Array<string>;
    totalPersons: bigint;
    totalAttendance: bigint;
    todayCheckins: bigint;
}
export interface PersonSummary {
    id: bigint;
    studentId: string;
    name: string;
    createdAt: Time;
    personType: PersonType;
    employeeId: string;
    batch: string;
    rollNo: string;
}
export type Time = bigint;
export interface AttendanceRecord {
    id: bigint;
    day: bigint;
    month: bigint;
    dateStr: string;
    name: string;
    slot: string;
    year: bigint;
    monthStr: string;
    personType: PersonType;
    personId: bigint;
    timestamp: Time;
    editedAt?: Time;
    timeStr: string;
}
export interface Person {
    id: bigint;
    studentId: string;
    name: string;
    createdAt: Time;
    personType: PersonType;
    employeeId: string;
    faceDescriptor: Array<number>;
    batch: string;
    rollNo: string;
}
export type PersonType = { 'employee': null } | { 'student': null };
export interface backendInterface {
    registerPerson(personTypeStr: string, studentId: string, employeeId: string, name: string, rollNo: string, batch: string, faceDescriptor: Array<number>): Promise<bigint>;
    getAllPersons(): Promise<Array<PersonSummary>>;
    getAllFaceDescriptors(): Promise<Array<DescriptorEntry>>;
    getPerson(id: bigint): Promise<Person>;
    getPersonSummary(id: bigint): Promise<PersonSummary>;
    updatePerson(id: bigint, studentId: string, employeeId: string, name: string, rollNo: string, batch: string): Promise<void>;
    updatePersonDescriptor(id: bigint, faceDescriptor: Array<number>): Promise<void>;
    deletePerson(id: bigint): Promise<void>;
    recordAttendance(personId: bigint, personTypeStr: string, name: string, slot: string, timestamp: bigint, dateStr: string, monthStr: string, timeStr: string, year: bigint, month: bigint, day: bigint): Promise<bigint>;
    getAttendanceRecords(): Promise<Array<AttendanceRecord>>;
    getAttendanceByDate(dateStr: string): Promise<Array<AttendanceRecord>>;
    getAttendanceByMonth(monthStr: string): Promise<Array<AttendanceRecord>>;
    updateAttendanceRecord(id: bigint, name: string, slot: string, dateStr: string, monthStr: string, timeStr: string): Promise<void>;
    deleteAttendanceRecord(id: bigint): Promise<void>;
    hasAttendedSlot(personId: bigint, slot: string, dateStr: string): Promise<boolean>;
    getStats(): Promise<Stats>;
    getTodayCheckins(dateStr: string): Promise<bigint>;
}
import type { AttendanceRecord as _AttendanceRecord, DescriptorEntry as _DescriptorEntry, Person as _Person, PersonSummary as _PersonSummary, PersonType as _PersonType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    private async _call<T>(fn: () => Promise<T>): Promise<T> {
        if (this.processError) {
            try {
                return await fn();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return fn();
    }

    async registerPerson(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<number>): Promise<bigint> {
        return this._call(() => this.actor.registerPerson(arg0, arg1, arg2, arg3, arg4, arg5, arg6));
    }
    async getAllPersons(): Promise<Array<PersonSummary>> {
        return this._call(async () => {
            const result = await this.actor.getAllPersons();
            return result.map((v) => from_candid_PersonSummary_n9(this._uploadFile, this._downloadFile, v));
        });
    }
    async getAllFaceDescriptors(): Promise<Array<DescriptorEntry>> {
        return this._call(async () => {
            const result = await this.actor.getAllFaceDescriptors();
            return result.map((v) => ({
                id: v.id,
                personType: from_candid_PersonType_n4(this._uploadFile, this._downloadFile, v.personType),
                name: v.name,
                faceDescriptor: v.faceDescriptor,
            }));
        });
    }
    async getPerson(arg0: bigint): Promise<Person> {
        return this._call(async () => {
            const result = await this.actor.getPerson(arg0);
            return from_candid_Person_n7(this._uploadFile, this._downloadFile, result);
        });
    }
    async getPersonSummary(arg0: bigint): Promise<PersonSummary> {
        return this._call(async () => {
            const result = await this.actor.getPersonSummary(arg0);
            return from_candid_PersonSummary_n9(this._uploadFile, this._downloadFile, result);
        });
    }
    async updatePerson(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        return this._call(() => this.actor.updatePerson(arg0, arg1, arg2, arg3, arg4, arg5));
    }
    async updatePersonDescriptor(arg0: bigint, arg1: Array<number>): Promise<void> {
        return this._call(() => this.actor.updatePersonDescriptor(arg0, arg1));
    }
    async deletePerson(arg0: bigint): Promise<void> {
        return this._call(() => this.actor.deletePerson(arg0));
    }
    async recordAttendance(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: bigint, arg10: bigint): Promise<bigint> {
        return this._call(() => this.actor.recordAttendance(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10));
    }
    async getAttendanceRecords(): Promise<Array<AttendanceRecord>> {
        return this._call(async () => {
            const result = await this.actor.getAttendanceRecords();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        });
    }
    async getAttendanceByDate(arg0: string): Promise<Array<AttendanceRecord>> {
        return this._call(async () => {
            const result = await this.actor.getAttendanceByDate(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        });
    }
    async getAttendanceByMonth(arg0: string): Promise<Array<AttendanceRecord>> {
        return this._call(async () => {
            const result = await this.actor.getAttendanceByMonth(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        });
    }
    async updateAttendanceRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        return this._call(() => this.actor.updateAttendanceRecord(arg0, arg1, arg2, arg3, arg4, arg5));
    }
    async deleteAttendanceRecord(arg0: bigint): Promise<void> {
        return this._call(() => this.actor.deleteAttendanceRecord(arg0));
    }
    async hasAttendedSlot(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        return this._call(() => this.actor.hasAttendedSlot(arg0, arg1, arg2));
    }
    async getStats(): Promise<Stats> {
        return this._call(() => this.actor.getStats());
    }
    async getTodayCheckins(arg0: string): Promise<bigint> {
        return this._call(() => this.actor.getTodayCheckins(arg0));
    }
}
function from_candid_AttendanceRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PersonSummary_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonSummary): PersonSummary {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PersonType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonType): PersonType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Person_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Person {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentId: string;
    name: string;
    createdAt: _Time;
    personType: _PersonType;
    employeeId: string;
    batch: string;
    rollNo: string;
}): {
    id: bigint;
    studentId: string;
    name: string;
    createdAt: Time;
    personType: PersonType;
    employeeId: string;
    batch: string;
    rollNo: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        name: value.name,
        createdAt: value.createdAt,
        personType: from_candid_PersonType_n4(_uploadFile, _downloadFile, value.personType),
        employeeId: value.employeeId,
        batch: value.batch,
        rollNo: value.rollNo
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    day: bigint;
    month: bigint;
    dateStr: string;
    name: string;
    slot: string;
    year: bigint;
    monthStr: string;
    personType: _PersonType;
    personId: bigint;
    timestamp: _Time;
    editedAt: [] | [_Time];
    timeStr: string;
}): {
    id: bigint;
    day: bigint;
    month: bigint;
    dateStr: string;
    name: string;
    slot: string;
    year: bigint;
    monthStr: string;
    personType: PersonType;
    personId: bigint;
    timestamp: Time;
    editedAt?: Time;
    timeStr: string;
} {
    return {
        id: value.id,
        day: value.day,
        month: value.month,
        dateStr: value.dateStr,
        name: value.name,
        slot: value.slot,
        year: value.year,
        monthStr: value.monthStr,
        personType: from_candid_PersonType_n4(_uploadFile, _downloadFile, value.personType),
        personId: value.personId,
        timestamp: value.timestamp,
        editedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.editedAt)),
        timeStr: value.timeStr
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentId: string;
    name: string;
    createdAt: _Time;
    personType: _PersonType;
    employeeId: string;
    faceDescriptor: Array<number>;
    batch: string;
    rollNo: string;
}): {
    id: bigint;
    studentId: string;
    name: string;
    createdAt: Time;
    personType: PersonType;
    employeeId: string;
    faceDescriptor: Array<number>;
    batch: string;
    rollNo: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        name: value.name,
        createdAt: value.createdAt,
        personType: from_candid_PersonType_n4(_uploadFile, _downloadFile, value.personType),
        employeeId: value.employeeId,
        faceDescriptor: value.faceDescriptor,
        batch: value.batch,
        rollNo: value.rollNo
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    employee: null;
} | {
    student: null;
}): PersonType {
    return value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
